# Rappels

In [6]:
## Créer un ndarray de taille 4
import numpy as np 

data_1 = [1.0, 3.5, 4.7, -5.1]
arr_1 = np.array(data_1)
print(arr_1)

[ 1.   3.5  4.7 -5.1]


In [34]:
## Créer un ndarray de taille 3*2 (3 lignes, 2 colonnes)
data = [
    [-10, -5],
    [-1, 2],
    [6, 11]
]

arr_2 = np.array(data)

arr_2

array([[-10,  -5],
       [ -1,   2],
       [  6,  11]])

In [8]:
# Format d'un array
arr_2.shape

(3, 2)

In [9]:
# Appliquer un masque simple
arr_2[arr_2 > 3] = 0
arr_2

array([[-10,  -5],
       [ -1,   2],
       [  0,   0]])

In [10]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 
arr_2 + 4

array([[-6, -1],
       [ 3,  6],
       [ 4,  4]])

In [11]:
# créer un nouvel array dont chacun des éléments est multiplié par 3
arr_2 * 3

array([[-30, -15],
       [ -3,   6],
       [  0,   0]])

# Exercices

In [33]:
# Appliquer un masque plus complexe : 
# A l'aide d'un masque, ré-assigner à 0 les valeurs strictement supérieures a 2 et les valeurs strictement inférieures à -2


arr_2[(arr_2 > 2) | (arr_2 < -2)] = 0 

arr_2

array([[ 0,  0],
       [-1,  2],
       [ 0,  0]])

In [22]:
# A l'aide de la fonction arange(), créer un array 1D avec les 7 premiers entiers

arr_7 = np.arange(7)
# Idem, mais le faire commencer à 3
arr_7_from_3 = np.arange(3, 10)
arr_7_from_3

# Créer un aray avec les 7 premiers nombres pairs
np.arange(0, 14, 2)


array([ 0,  2,  4,  6,  8, 10, 12])

In [23]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 

arr_1 + 2

array([ 3. ,  5.5,  6.7, -3.1])

In [24]:
# Reprendre un des arrays précédents, et l'utiliser pour créer un nouvel array dont chacun des éléments est multiplié par 5

arr_7_from_3 * 5

array([15, 20, 25, 30, 35, 40, 45])

In [25]:
# A l'aide de la méthode .arange() et de la méthode .reshape(), 
# créer une matrice de 3 lignes et 6 colonnes remplie des entiers allant de 0 à 17

np.arange(18).reshape((3, 6))


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [32]:
# Note : possible aussi d'utiliser linspace()
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])