# Rappels

In [2]:
## Créer un ndarray de taille 4
import numpy as np 

data_1 = [1.0, 3.5, 4.7, -5.1]
arr_1 = np.array(data_1)
print(arr_1)

[ 1.   3.5  4.7 -5.1]


In [ ]:
## Créer un ndarray de taille 3*2 (3 lignes, 2 colonnes)
data = [
    [-10, -5],
    [-1, 2],
    [6, 11]
]

arr_2 = np.array(data)

arr_2

array([[-10,  -5],
       [ -1,   2],
       [  6,  11]])

In [ ]:
# Format d'un array
arr_2.shape

(3, 2)

In [ ]:
# Appliquer un masque simple
arr_2[arr_2 > 3] = 0
arr_2

array([[-10,  -5],
       [ -1,   2],
       [  0,   0]])

In [ ]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 
arr_2 + 4

In [ ]:
# créer un nouvel array dont chacun des éléments est multiplié par 3
arr_2 * 3

# Exercices

In [21]:
# Appliquer un masque plus complexe : 
# A l'aide d'un masque, ré-assigner à 0 les valeurs strictement supérieures a 2 et les valeurs strictement inférieures à -2
arr_1[(arr_1 > 2) | (arr_1 < -2)] = 0 
arr_1

array([[ 0,  0],
       [-1,  2],
       [ 0,  0]])

In [3]:
# A l'aide de la fonction arange(), créer un array 1D avec les 7 premiers entiers
arr_7_first = np.arange(7)
print(arr_7_first)
# Idem, mais le faire commencer à 3
arr_3_7 = np.arange(3, 10)
print(arr_3_7)

# Créer un aray avec les 7 premiers nombres pairs
arr_7_even = np.arange(0, 14, 2)
print(arr_7_even)

[0 1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12]


In [4]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 
arr_7_first + 3

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reprendre un des arrays précédents, et l'utiliser pour créer un nouvel array dont chacun des éléments est multiplié par 5
arr_7_first * 5

array([ 0,  5, 10, 15, 20, 25, 30])

In [ ]:
# A l'aide de la méthode .arange() et de la méthode .reshape(), 
# créer une matrice de 3 lignes et 6 colonnes remplie des entiers allant de 0 à 17


np.arange(18).reshape(3,6)

In [ ]:
# Note : possible aussi d'utiliser linspace()