# Rappels

In [18]:
## Créer un ndarray de taille 3*2 (3 lignes, 2 colonnes)
import numpy as np 
data = [
    [-10, -5],
    [-1, 2],
    [6, 11]
]

arr_1 = np.array(data)

arr_1

array([[-10,  -5],
       [ -1,   2],
       [  6,  11]])

In [19]:
# Format d'un array
arr_1.shape

(3, 2)

In [20]:
# Appliquer un masque simple
arr_1[arr_1 > 3] = 0
arr_1

array([[-10,  -5],
       [ -1,   2],
       [  0,   0]])

# Exercices

In [21]:
# Appliquer un masque plus complexe : 
# A l'aide d'un masque, ré-assigner à 0 les valeurs strictement supérieures a 2 et les valeurs strictement inférieures à -2
arr_1[(arr_1 > 2) | (arr_1 < -2)] = 0 
arr_1

array([[ 0,  0],
       [-1,  2],
       [ 0,  0]])

In [22]:
# Créer un array 1D avec les 7 premiers entiers
arr_7_first = np.arange(7)
print(arr_7_first)
# Idem, mais le faire commencer à 3
arr_3_7 = np.arange(3, 10)
print(arr_3_7)

# Créer un aray avec les 7 premiers nombres pairs
arr_7_even = np.arange(0, 14, 2)
print(arr_7_even)

[0 1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12]


In [23]:
# Que se passe-t-il si on additionne un array avec un nombre (int) ? 
arr_7_first + 3

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
# Reprendre un des arrays précédents, et l'utiliser pour créer un nouvel array dont chacun des éléments est multiplié par 2
arr_7_first * 2

array([ 0,  2,  4,  6,  8, 10, 12])